title: "h3110-y0u-4r3-4w350m3"
description: "Solve like a flash"
hint: "Solve the equation and send the result in the result variable"
template: "h3110-y0u-4r3-4w350m3.html"
css: "./static/h3110-y0u-4r3-4w350m3-style.css"
javascript: "./static/h3110-y0u-4r3-4w350m3-script.js"
