title: "My own browser"
description: "Only my browser is allow"
hint: "Change the User-Agent to anything with ${TARGET_NAME} in it (both lowercase/uppercase works)"
template: "x0r-15-n0t-m1l1t4ry-gr4d3-3ncrypt10n.html"
css: "./static/x0r-15-n0t-m1l1t4ry-gr4d3-3ncrypt10n-style.css"
javascript: "./static/x0r-15-n0t-m1l1t4ry-gr4d3-3ncrypt10n-script.js"
