title: "ch00Z3-uR-PASS"
description: "Fromage ou dessert ?"
hint: "Clic on the chosen track (you might inspect the link and use the href)"
template: "ch00Z3-uR-PASS.html"
css: "./static/ch00Z3-uR-PASS-style.css"
javascript: "./static/ch00Z3-uR-PASS-script.js"
