title: "plus_or_minus"
description: "Find the number !"
hint: "Follow the instructions and create a small program to find the right number between 0 and 1000000 with only 25 tries + 25 seconds (dichotomy powa)"
template: "us3r-4g3n7-15-4n-1n73rn4710n4l-574nd4rd.html"
css: "./static/us3r-4g3n7-15-4n-1n73rn4710n4l-574nd4rd-style.css"
javascript: "./static/us3r-4g3n7-15-4n-1n73rn4710n4l-574nd4rd-style.css"
api: "api.py"
