title: "7h3-4n5w3r-15-4-5h4m3"
description: "Fromage ou dessert ?"
hint: "retrieve the Javascript and XOR the bytes with the defined function"
template: "7h3-4n5w3r-15-4-5h4m3.html"
css: "./static/7h3-4n5w3r-15-4-5h4m3-style.css"
javascript: "./static/7h3-4n5w3r-15-4-5h4m3-script.js"
