name: Vercel Action

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Vercel Action
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: Kw2y45KugdS7jjbHkCkM7vOG
